# ============================================================================
# REPLACE THIS FILE.
#
# This file is auto-generated by the NixOS installer for your specific disk
# layout, kernel modules, and filesystems. Don't write it by hand.
#
# To generate the real one:
#   sudo nixos-generate-config --root /mnt   # during install
# or, on an already-installed system:
#   sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix
#
# Then copy the generated /etc/nixos/hardware-configuration.nix here, replacing
# this placeholder.
# ============================================================================
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Example shape — yours will differ:
  # boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" ];
  # fileSystems."/" = { device = "/dev/disk/by-uuid/..."; fsType = "ext4"; };
  # fileSystems."/boot" = { device = "/dev/disk/by-uuid/..."; fsType = "vfat"; };
  # swapDevices = [ ];

  nixpkgs.hostPlatform = "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # If Intel: hardware.cpu.intel.updateMicrocode = ...
}
